// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { id: bigint, theme_style: string, theme_mode: string, accent: string, sidebar_hidden: boolean, graph_node_color: string, graph_link_color: string, graph_node_size: number, graph_link_width: number, graph_show_labels: boolean, graph_label_size: number, graph_show_legend: boolean, graph_show_topology: boolean, };
