// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageInput } from "./ChatMessageInput";

export type ChatRequest = { model: string, messages: Array<ChatMessageInput>, temperature: number | null, max_tokens: number | null, };
