// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DDay = { id: bigint, title: string, target_date: string, color: string | null, created_at: string | null, };
