// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkV2 = { id: bigint, source_id: bigint, target_id: bigint, type_id: bigint | null, strength: number, bidirectional: boolean, created_at: string | null, };
