// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlannerEvent = { id: bigint, repository_id: bigint | null, title: string, description: string | null, start_at: string, end_at: string, recurrence: string | null, };
