// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResourceMetadata = { resource_id: bigint, importance: number, status: string, difficulty: string, time_estimate: number, last_reviewed_at: string | null, };
