// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceIdentity = { device_id: string, device_name: string | null, platform: string, created_at: string | null, last_seen_at: string | null, is_active: boolean, };
