// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceRegistration = { device_id: string, device_name: string, platform: string, user_id: string, };
