// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncryptionStatus = { is_encrypted: boolean, encryption_version: string | null, migration_applied_at: string | null, };
