// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FinanceSummary = { total_net_worth: number, monthly_income: number, monthly_spent: number, income_change_pct: number, net_worth_history: Array<number>, };
