// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Lecture = { id: bigint, repository_id: bigint, title: string, url: string, thumbnail: string | null, group_name: string | null, is_completed: boolean, order_index: number | null, };
