// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrationConflict = { id: string, table_name: string, record_id: string, local_data: string, cloud_data: string, conflict_type: string, resolution: string | null, };
