// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrationEligibility = { is_eligible: boolean, reasons: Array<string>, data_size_estimate: bigint, requires_premium: boolean, };
