// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrationProgress = { phase: string, completed_steps: Array<string>, total_steps: number, bytes_uploaded: bigint, conflicts_detected: number, estimated_time_remaining: number | null, progress_percentage: number, };
