// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Repository = { id: bigint, name: string, code: string | null, semester: string | null, description: string | null, credits: number, semester_id: bigint | null, manual_grade: number | null, status: string, component_config: string | null, component_scores: string | null, grading_scale_id: bigint | null, };
