// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Resource = { id: bigint, repository_id: bigint | null, title: string, type: string, path: string | null, content: string | null, tags: string | null, created_at: string | null, };
