// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SavingsGoal = { id: bigint | null, name: string, target_amount: number, current_amount: number, deadline: string | null, };
