// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StudySession = { id: bigint, repository_id: bigint | null, start_at: string, end_at: string | null, duration: number | null, is_break: boolean, created_at: string | null, };
