// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncState = { is_sync_enabled: boolean, supabase_user_id: string | null, last_synced_at: string | null, sync_protocol_version: number, is_premium_active: boolean, device_id: string | null, };
