// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPublic = { id: bigint, username: string, created_at: string | null, is_cloud_user: boolean, };
